# Uncomment the next line to define a global platform for your project
# platform :ios, "8.0'

target 'xianchufang' do
  pod "MJRefresh","~>3.1.12"
  pod "Masonry","~>1.0.2"
  pod "AFNetworking","~>3.1.0"
  pod "SDWebImage","~>4.0.0-beta2"
 # pod "KeyBoard","~>0.5.0"
 # pod 'Keyboard', '~> 0.5.0'
  pod "PinYin4Objc","~>1.1.1"
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xianchufang

  target 'xianchufangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xianchufangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
